name: gen-checker

on:
  pull_request:

jobs:
  oapi-codegen-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.18"

      - name: set up
        run: install_oapi_codegen

      - name: codegen check
        run: sh scripts/oapi-codegen-checker.sh
